spring:
  application:
    name: ProdutoEstoqueapi
  datasource:
    url: jdbc:postgresql://localhost:5432/estoqueDeProdutos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
